### ISSUE TITLE
Lua error on completing a mission.

### ISSUE THREAD

**Issue by ylcard** [alarofrunetotem/ChampionCommander#10]
`Message: ...rface\AddOns\ChampionCommander\ChampionCommander.lua:460: bad argument #2 to 'strsplit' (string expected, got nil)
Time: Mon Sep  3 22:33:23 2018
Count: 1
Stack: ...rface\AddOns\ChampionCommander\ChampionCommander.lua:460: bad argument #2 to 'strsplit' (string expected, got nil)
[C]: ?
[C]: in function `strsplit'
...rface\AddOns\ChampionCommander\ChampionCommander.lua:460: in function <...rface\AddOns\ChampionCommander\ChampionCommander.lua:446>

Locals: `

Happened when I completed the BfA mission about Nature Calls or something, that rewards an upgraded outpost in Kul Tiras, Swiftwind Post.

**Comment by alar77** [comment]
Will try a "generic fix" cause I am lagging very behind in BFA progression

**Comment by alar77** [comment]
Fixed
