### ISSUE TITLE
Max Reputation

### ISSUE THREAD

**Issue by Sooleawa** [alarofrunetotem/ChampionCommander#11]
When you are exalted,  i feel the the reward for doing those reputation missions are greatly diminished.  I have started to manually blacklist them. But maybe a filter option for exalted statuses,  or some logic that pushes exalted ones to low priority would be nice.
This is just a suggestion ;)

**Comment by alar77** [comment]
Nice idea, lot of work. Marking as enhancement

**Comment by Sooleawa** [comment]
Read somewhere that later they bring back paragon reputation rewards (no mounts), and account bound tokens at max reputation??? i am not sure,  but if it's true, it may be worth to just wait it out.

**Comment by alar77** [comment]
Fixed 1.2.2
