### ISSUE TITLE
attempt to index field 'Left' (a nil value)

### ISSUE THREAD

**Issue by Ookami313** [alarofrunetotem/ChampionCommander#12]
Updated to 1.1.0Alpha and received the following error when I opened the mission table. 

Date: 2018-09-09 17:26:41
ID: 2
Error occured in: Global
Count: 1
Message: ...ce\AddOns\ChampionCommander\libs\LibInit\factory.lua line 282:
   attempt to index field 'Left' (a nil value)
Debug:
   (tail call): ?
   [C]: ?
   ...ce\AddOns\ChampionCommander\libs\LibInit\factory.lua:282: DropDown()
   ...ce\AddOns\ChampionCommander\libs\LibInit\factory.lua:356: Option()
   ChampionCommander\missionlist.lua:678: Menu()
   ChampionCommander\missionlist.lua:741:
      ChampionCommander\missionlist.lua:736
   (tail call): ?
   [C]: ?
   [C]: Show()
   ..\FrameXML\UIParent.lua:2614: SetUIPanel()
   ..\FrameXML\UIParent.lua:2420: ShowUIPanel()
   ..\FrameXML\UIParent.lua:2320:
      ..\FrameXML\UIParent.lua:2316
   [C]: SetAttribute()
   ..\FrameXML\UIParent.lua:3141:
      ..\FrameXML\UIParent.lua:3129
   [C]: ShowUIPanel()
   ..\FrameXML\UIParent.lua:1724:
      ..\FrameXML\UIParent.lua:1090
Locals:
(*temporary) = <function> defined =[C]:-1

AddOns:

**Comment by R-Adrian** [comment]
getting the same...

```
Date: 2018-09-10 21:54:12
ID: 1
Error occured in: Global
Count: 1
Message: ...ce\AddOns\ChampionCommander\libs\LibInit\factory.lua line 282:
   attempt to index field 'Left' (a nil value)
Debug:
   [C]: ?
   ...ce\AddOns\ChampionCommander\libs\LibInit\factory.lua:282: DropDown()
   ...ce\AddOns\ChampionCommander\libs\LibInit\factory.lua:356: Option()
   ChampionCommander\missionlist.lua:678: Menu()
   ChampionCommander\missionlist.lua:741:
      ChampionCommander\missionlist.lua:736
   (tail call): ?
   [C]: ?
   [C]: Show()
   ..\FrameXML\UIParent.lua:2614: SetUIPanel()
   ..\FrameXML\UIParent.lua:2420: ShowUIPanel()
   ..\FrameXML\UIParent.lua:2320:
      ..\FrameXML\UIParent.lua:2316
   [C]: SetAttribute()
   ..\FrameXML\UIParent.lua:3141: ShowUIPanel()
   ..\FrameXML\UIParent.lua:1724:
      ..\FrameXML\UIParent.lua:1090
Locals:

```

**Comment by Zarggg** [comment]
According to comments on the Curse page, it looks like an incompatibility with the embedded LibInit library. As a side effect, there is an unusable drop-down menu appearing in the bottom left of my screen.

**Comment by alar77** [comment]
Fixed in Beta-2
