### ISSUE TITLE
Bugs with latest alpha

### ISSUE THREAD

**Issue by Addonman** [alarofrunetotem/ChampionCommander#13]
Error occured in: Global
Count: 1
Message: ...ce\AddOns\ChampionCommander\libs\LibInit\factory.lua line 282:
   attempt to index field 'Left' (a nil value)
Debug:
   [C]: ?
   ...ce\AddOns\ChampionCommander\libs\LibInit\factory.lua:282: DropDown()
   ...ce\AddOns\ChampionCommander\libs\LibInit\factory.lua:356: Option()
   ChampionCommander\missionlist.lua:678: Menu()
   ChampionCommander\missionlist.lua:741:
      ChampionCommander\missionlist.lua:736
   (tail call): ?
   [C]: ?
   [C]: Show()
   ..\FrameXML\UIParent.lua:2614: SetUIPanel()
   ..\FrameXML\UIParent.lua:2420: ShowUIPanel()
   ..\FrameXML\UIParent.lua:2320:
      ..\FrameXML\UIParent.lua:2316
   [C]: SetAttribute()
   ..\FrameXML\UIParent.lua:3141:
      ..\FrameXML\UIParent.lua:3129
   [C]: ShowUIPanel()
   ..\FrameXML\UIParent.lua:1724:
      ..\FrameXML\UIParent.lua:1090
   [C]: ?
Locals:

Error occured in: Global
Count: 3
Message: ..\AddOns\ChampionCommander\missionlist.lua line 317:
   attempt to index field 'allArtifactPower' (a nil value)
Debug:
   [C]: ?
   ChampionCommander\missionlist.lua:317:
      ChampionCommander\missionlist.lua:314
   (tail call): ?
   [C]: ?

Error occured in: Global
Count: 1
Message: ..\AddOns\ChampionCommander\missionpage.lua line 392:
   attempt to get length of local 'party' (a nil value)
Debug:
   [C]: ?
   ChampionCommander\missionpage.lua:392: FillParty()
   ChampionCommander\missionpage.lua:154:
      ChampionCommander\missionpage.lua:111
   (tail call): ?
   (tail call): ?
   [C]: Click()
   ...e\AddOns\GarrisonMissionManager\MissionUI_Shared.lua:235:
      ...e\AddOns\GarrisonMissionManager\MissionUI_Shared.lua:225

**Comment by Zarggg** [comment]
Previously reported in #12. Appears to be the exact same exception. According to comments on the Curse page, it looks like an incompatibility with the embedded LibInit library.
