### ISSUE TITLE
choosing champion bug

### ISSUE THREAD

**Issue by wolfrunner86** [alarofrunetotem/ChampionCommander#14]
used the classhall version all threw legion and loved it figured i would give this a chance.
with this one i am noticing that i am having to cycle threw the check boxes to find an appropriate  set.
![bfa table](https://user-images.githubusercontent.com/7499021/45372702-a36ad700-b5bb-11e8-8085-ee2bd362d263.png)

**Comment by Zarggg** [comment]
This is a known issue with version 1.0.3. A workaround is to close the mission window after sending off each mission.

**Comment by alar77** [comment]
Fixed in 1.1.1
