### ISSUE TITLE
Betas not working for me?

### ISSUE THREAD

**Issue by Sooleawa** [alarofrunetotem/ChampionCommander#18]
*****  close this if not relevant to development ******
opening table,  those suggestions are completely missing,  also going into any mission does not fill roster.
Additionally opening tables sometimes just freezes wow, sometimes for a good 20-30 seconds,  sometimes completely. No error showing on screen.
Did this on beta 3,  but beta 2 was the same. gone back to 1.0.3 release always fixes it.
![wowscrnshot_100618_074139](https://user-images.githubusercontent.com/38173931/46575975-2b2be180-c9c0-11e8-85c2-a76eacd2a7cf.jpg)

**Comment by alar77** [comment]
There was a lua error,m probably the one raised with #17

**Comment by Sooleawa** [comment]
Beta 4 showing correctly
