### ISSUE TITLE
Lua error causes into WoW crash

### ISSUE THREAD

**Issue by Evelgest** [alarofrunetotem/ChampionCommander#19]
When i click an the BFA misssion table i receive one Lua error. Close them and select a mission WoW freeze and drop after kill WoW prozess to the destkop.
Closing the lua-error and select a mission get a mission without preselected champions. 
Select the preset champions for the mission, the button "Start Mission" is greyed out and WoW stoped working and hat to kill.
Empty Preselection:
![empty preselect](https://user-images.githubusercontent.com/44003558/46691088-4e46d300-cc04-11e8-8e09-1ef6372aef8f.png)

Select 200% without time bonus
![grafik](https://user-images.githubusercontent.com/44003558/46691191-982fb900-cc04-11e8-9c59-bad28125e622.png)

Thank you for this Addon an your work.

Best regards from Gemany
Frank

(German client)
The lua-error:
Date: 2018-10-09 20:35:31
ID: 3
Error occured in: Global
Count: 1
Message: ..\AddOns\ChampionCommander\missionlist.lua line 317:
   attempt to index field 'allArtifactPower' (a nil value)
Debug:
   ChampionCommander\missionlist.lua:317:
      ChampionCommander\missionlist.lua:314
   (tail call): ?
   [C]: ?
Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\ArathiRareTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:398
 EnableModule = <function> defined @Interface\AddOns\ArathiRareTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:363
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface\AddOns\ArathiRareTracker\Libs\AceTimer-3.0\AceTimer-3.0.lua:147
 IterateEmbeds = <function> defined @Interface\AddOns\ArathiRareTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:473
 SecureHook = <function> defined @Interface\AddOns\CollectMe\Libs\AceHook-3.0\AceHook-3.0.lua:336
 MissionTip = <function> defined @Interface\AddOns\ChampionCommander\missionlist.lua:1189
 RawHookScript = <function> defined @Interface\AddOns\CollectMe\Libs\AceHook-3.0\AceHook-3.0.lua:395
 SortMissions = <function> defined @Interface\AddOns\ChampionCommander\missionlist.lua:444
 NoMartiniNoParty = <function> defined @Interface\AddOns\ChampionCommander\missionlist.lua:618
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\ArathiRareTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:440
 Menu = <function> defined @Interface\AddOns\ChampionCommander\missionlist.lua:696
 IsEnabled = <function> defined @Interface\AddOns\ArathiRareTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:482
 ScheduleTimer = <function> defined @Interface\AddOns\ArathiRareTracker\Libs\AceTimer-3.0\AceTimer-3.0.lua:94
 DisableModule = <function> defined @Interface\AddOns\ArathiRareTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:381
 RegisterMessage = <function> defined @Interface\AddOns\AllTheThings\lib\CallbackHandler-1.0\CallbackHandler-1.0.lua:118
 UnregisterMessage = <function> defined @Interface\AddOns\AllTheThings\lib\CallbackHandler-1.0\CallbackHandler-1.0.lua:181
 IsHooked = <function> defined @Interface\AddOns\CollectMe\Libs\AceHook-3.0\AceHook-3.0.lua:493
 InitialSetup = <function> defined @Interface\AddOns\ChampionCommander\missionlist.lua:736
 SetEnabledState = <function> defined @Interface\AddOns\ArathiRareTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:455
 Hook = <function> defined @Interface\AddOns\CollectMe\Libs\AceHook-3.0\AceHook-3.0.lua:274
 enabledState = true
 RegisterEvent = <function> defined @Interface\AddOns\AllTheThings\lib\CallbackHandler-1.0\CallbackHandler-1.0.lua:118
 SelectTab = <function> defined @Interface\AddOns\ChampionCommander\missionlist.lua:825
 IterateModules = <function> defined @Interface\AddOns\ArathiRareTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:468
 Dim = <function> defined @Interface\AddOns\ChampionCommander\missionlist.lua:951
 RawHook = <function> defined @Interface\AddOns\CollectMe\Libs\AceHook-3.0\AceHook-3.0.lua:313
 DisplayMenu = <function> defined @Interface\AddOns\ChampionCommander\missionlist.lua:725
 OnInitialize = <function> defined @Interface\AddOns\ChampionCommander\libs\LibInit\LibInit.lua:402
 UnregisterAllEvents = <function> defined @Interface\AddOns\AllTheThings\lib\CallbackHandler-1.0\CallbackHandler-1.0.lua:202
 GetModule = <function> defined @Interface\AddOns\ArathiRareTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:241
 LoadButtons = <function> defined @Interface\AddOns\ChampionCommander\missionlist.lua:268
 defaultModuleLibraries = <table> {
 }
 OnUpdate = <function> defined @Interface\AddOns\ChampionCommander\missionlist.lua:367
 ScheduleRepeatingTimer = <function> defined @Interface\AddOns\ArathiRareTracker\Libs\AceTimer-3.0\AceTimer-3.0.lua:129
 CancelAllTimers = <function> defined @Interface\AddOns\ArathiRareTracker\Libs\AceTimer-3.0\AceTimer-3.0.lua:160
 baseName = "Blizzard_OrderHallUI"
 GetName = <function> defined @Interface\AddOns\ArathiRareTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:310
 hooks = <table> {
 }
 AdjustMissionTooltip = <function> defined @Interface\AddOns\ChampionCommander\missionlist.lua:1233
 AddThreats = <function> defined @Interface\AddOns\ChampionCommander\missionlist.lua:1087
 Events = <function> defined @Interface\AddOns\ChampionCommander\missionlist.lua:253
 AddMembers = <function> defined @Interface\AddOns\ChampionCommander\missionlist.lua:984
 EvOff = <function> defined @Interface\Add
AddOns:
  Swatter, v8.0.6162 (SwimmingSeadragon)
  NPCScanOverlay, v7.3.0.1
  AllTheThings, v1.7.3b
  ArathiRareTracker, v0.7.0
  AucAdvanced, v8.0.6122 (SwimmingSeadragon)
  AucFilterBasic, v8.0.6149 (SwimmingSeadragon)
  AucStatHistogram, v8.0.6151 (SwimmingSeadragon)
  AucStatiLevel, v8.0.6155 (SwimmingSeadragon)
  AucStatPurchased, v8.0.6152 (SwimmingSeadragon)
  AucStatSimple, v8.0.6153 (SwimmingSeadragon)
  AucStatStdDev, v8.0.6154 (SwimmingSeadragon)
  AucUtilFixAH, v8.0.6156 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.0.6
  BankStack, vv39-1-g0868fca
  BattlePetDailyTamer, v3.0.4
  BattlePetBattleStats, v1.0.11
  BattlePetBreedID, vr179
  BeanCounter, v8.0.6157 (SwimmingSeadragon)
  BigWigs, vv120
  BtWObjectiveFilter, v1.2
  BtWQuests, v1.26
  BtWQuestsBattleForAzeroth, v16
  CensusPlus, v8.0.
  ChampionCommander, v1.1.0-Beta-2 80000
  CollectMe, v2.10.1
  Critline, vr137
  CritlineAuraMonitor, vr137
  DerangementPetBattleCooldowns, vv1.1.4
  Details, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTimeAttack, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  DraenorTreasures, v8.0.1.27144
  Enchantrix, v8.0.6158 (SwimmingSeadragon)
  GarrisonCommander, v3.0.0 70200
  GarrisonCommanderBroker, v3.0.0 1.1.0
  GarrisonMissionManager, vv58
  GatherMate2, v1.43.4
  GatherMateSharing, vv1.11
  Hekili, vv8.0.1-36-5-g4e19fde
  ImprovedOptionsFrames, v1.5.6
  Informant, v8.0.6159 (SwimmingSeadragon)
  InstancePortals, v19
  MasterPlanA, vA
  NPCScan, v8.0.1.13
  Omen, v3.2.0
  OrderHallCommander, v1.7.2 80000
  Overachiever, v1.0.5
  OverachieverCache, v1.0.5
  OverachieverTabs, v1.0.5
  Pawn, v2.2.29
  PetBattleTeams, v3.3.10
  PetJournalEnhanced, v2.9.30
  PetTracker, v8.0.6
  PetTrackerBreeds, v8.0.6
  PetTrackerJournal, v8.0.6
  PetTrackerSwitcher, v8.0.6
  PetTrackerUpgrades, v8.0.6
  PokemonTrainer, v8.0.7
  Postal, vv3.6.0
  QuestCompletist, v108.17
  Rarity, v1.0 (r680-release)
  RarityOptions, v
  Rematch, v4.8.9
  SavedInstances, v8.0.6-1-g3950175
  SexyMap, vv8.0.8
  SilverDragon, vv4.0.13-20-g5a6dee4
  SilverDragonBattleForAzeroth, vv4.0.13-20-g5a6dee4
  SilverDragonBurningCrusade, vv4.0.13-20-g5a6dee4
  SilverDragonCataclysm, vv4.0.13-20-g5a6dee4
  SilverDragonLegion, vv4.0.13-20-g5a6dee4
  SilverDragonMists, vv4.0.13-20-g5a6dee4
  SilverDragonVanilla, vv4.0.13-20-g5a6dee4
  SilverDragonWarlords, vv4.0.13-20-g5a6dee4
  SilverDragonWrath, vv4.0.13-20-g5a6dee4
  Stubby, v8.0.6161 (SwimmingSeadragon)
  TheUndermineJournal, v5.4.20181009
  Titan, v5.14.11.80000
  TitanBag, v5.14.11.80000
  TitanClock, v5.14.11.80000
  TitanGold, v5.14.11.80000
  TitanLocation, v5.14.11.80000
  TitanLootType, v5.14.11.80000
  TitanPerformance, v5.14.11.80000
  TitanRepair, v5.14.11.80000
  TitanVolume, v5.14.11.80000
  TitanXP, v5.14.11.80000
  TransmogTokens, v1.4.9
  WorldQuestsList, v81
  WorldQuestTracker, v
  BlizRuntimeLib_deDE v8.0.1.80000 <none>
  (ck=b99)

**Comment by Zarggg** [comment]
This error has been fixed as of Beta 4. You are currently using Beta 2.

**Comment by Evelgest** [comment]
Thank you.
Close
