### ISSUE TITLE
Analyze Parties doesn't find all combinations

### ISSUE THREAD

**Issue by FuxieDK** [alarofrunetotem/ChampionCommander#20]
I found a combination that wasn't found by the addon, but was available anyway..

A 190% combination is too good to miss.

![wowscrnshot_101218_163102](https://user-images.githubusercontent.com/44226521/47100162-2aecdb00-d237-11e8-8fbb-e4f4bd6b4a4d.jpg)

**Comment by alar77** [comment]
Mission is there. In party analisys when it comes to troop it just select a compatible one, regardless of busy status. When you assign it, it will hunt for an  available troop
