### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Ookami313** [alarofrunetotem/ChampionCommander#21]
Any chance of adding the ability for the addon to notify you some home (like via an icon or something) if a quest on your mission table is available that counts towards the Azeroth at War: The Barrens, After Lorderon, and Kalimdor on Fire achievements and you haven't completed it yet. Currently I have to swap back and forth between opening the mission table UI and the achievement UI (neither of which will stay open at the same time as the other) while seeing if I have a quest available that I need for the achievements that I can send followers on. 

Thanks.

**Comment by alar77** [comment]
Alas, this is out of the scope of the addon and will require a huge amount of work to keep pace with new lores added by Blizzard in time.
Sorry
