### ISSUE TITLE
Scouting Map broken

### ISSUE THREAD

**Issue by syndenbock** [alarofrunetotem/ChampionCommander#23]
When having ChampionCommander enabled, I cannot select a zone on the scouting map in Boralus.
When disabling the addon, it works again.

**Comment by syndenbock** [comment]
Update: The problematic line is in "core.lua" line 138. The Frame needs to have the mouse enabled even after moving. If I comment out this line, the scouting map works just fine.

**Comment by mark-russ** [comment]
Can confirm the same, zones on the scouting map do not respond to mouse events (hover or click) while this addon is active.

**Comment by alar77** [comment]
I could never replicate this issue. Let me check core.lua anyway

**Comment by alar77** [comment]
Good call mate, I always leave the panel movable so It was not hurting me at all.
