### ISSUE TITLE
equip bug

### ISSUE THREAD

**Issue by Mondoblasto** [alarofrunetotem/ChampionCommander#25]
Attempt to equip champ via mission command table or minimap button, /reload causes it to work one time for each equipment.

<s>lost info due to signing up to github</s>

Date: 2019-03-19 23:08:30
ID: 4
Error occured in: AddOn: ChampionCommander
Count: 1
Message: Error: AddOn ChampionCommander attempted to call a forbidden function (CastItemSpellOnFollowerAbility()) from a tainted execution path.
Debug:
   [C]: CastItemSpellOnFollowerAbility()
   ...rrisonTemplates\Blizzard_GarrisonSharedTemplates.lua:59: OnAccept()
   ..\FrameXML\StaticPopup.lua:5053: StaticPopup_OnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:
None
AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  WowheadLooter, v80100
  NPCScanOverlay, v7.3.0.1
  Ace3, v
  ACP, vr259 
  Atlas, vv1.44.06
  AtlasBattlegrounds, vv1.44.01
  AtlasBurningCrusade, vv1.44.01
  AtlasCataclysm, vv1.44.01
  AtlasClassicWoW, vv1.44.01
  AtlasClassOrderHalls, vv1.44.01
  AtlasDungeonLocs, vv1.44.01
  AtlasLegion, vv1.44.01
  AtlasMistsofPandaria, vv1.44.01
  AtlasOutdoorRaids, vv1.44.01
  AtlasScenarios, vv1.44.00
  AtlasTransportation, vv1.44.01
  AtlasWarlordsofDraenor, vv1.44.01
  AtlasWrathoftheLichKing, vv1.44.01
  AtlasLoot, vv8.09.00
  AtlasLootBattleforAzeroth, vv8.09.00
  AtlasLootBurningCrusade, vv8.09.00
  AtlasLootCataclysm, vv8.09.00
  AtlasLootClassic, vv8.09.00
  AtlasLootLegion, vv8.09.00
  AtlasLootMistsofPandaria, vv8.09.00
  AtlasLootWarlordsofDraenor, vv8.09.00
  AtlasLootWrathoftheLichKing, vv8.09.00
  AtlasQuest, v4.11.00
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucScanData, v8.1.6229 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  BagSync, v11.1
  BarovHelper, v
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  Capping, vv8.1.1
  ChampionCommander, v1.1.2 80100
  CloseUp, v8.0.001
  DBMCore, v8.1.12
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DefsCameraZoom, v80100.1
  Enchantrix, v8.1.6237 (SwimmingSeadragon)
  FBBroker, v1.34.12
  FBOutfitDisplayFrame, v1.9.5
  FBTitan, v1.0.17
  FBTrackingFrame, v1.9.1
  FishingBuddy, v1.9.27
  GarrisonCommander, v3.0.2 70200
  GarrisonCommanderBroker, v3.0.2 1.1.0
  HandyNotes, vv1.5.5
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesDraenorTreasures, v1.21
  HandyNotesEverShiftingMirror, v1.0.3
  HandyNotesLegionTreasures, v1
  HandyNotesWarfrontRares, v0.5.0
  Informant, v8.1.6246 (SwimmingSeadragon)
  IskarAssist, v
  KHunterTimers, v4.3.1
  LinkWrangler, v2.01
  LinkWranglerAuctioneer, v1.68
  LinkWranglerCompanion, v1.81
  NPCScan, v8.0.1.13
  Omen, v3.2.0
  OrderHallCommander, v1.7.3 80100
  Overachiever, v1.0.5
  OverachieverCache, v1.0.5
  OverachieverTabs, v1.0.5
  OverachieverTrade, v1.0.5
  PassLoot, v4.4
  Paste, v1.4.10
  Pawn, v2.2.39
  Possessions, vr16
  ProfessionsVault, v7.1.9
  QuestGuru, v2.5.15
  QuestGuruSounds, v2.5.15
  RaidAssist, v
  SimPermut, v1.15.0
  SlideBar, v8.1.6239 (SwimmingSeadragon)
  Stubby, v8.1.6240 (SwimmingSeadragon)
  Titan, v5.17.0.80100
  TitanBag, v5.17.0.80100
  TitanClock, v5.17.0.80100
  TitanGold, v5.17.0.80100
  TitanLocation, v5.17.0.80100
  TitanLootType, v5.17.0.80100
  TitanPerformance, v5.17.0.80100
  TitanRepair, v5.17.0.80100
  TitanVolume, v5.17.0.80100
  TitanXP, v5.17.0.80100
  TomTom, vv80105-1.0.0
  WorldBossStatus, vv6.0.6
  WorldBossTimers, v0.1
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=bb6)

**Comment by alar77** [comment]
A known issue, also documented. Blizzard taint is crap. No way I can fix it. DO not drag and drop items, just right click and then click on slot
