### ISSUE TITLE
Can't handle stealth missions

### ISSUE THREAD

**Issue by cremor** [alarofrunetotem/ChampionCommander#3]
There are missions of the type [stealth](https://www.wowhead.com/threat=153/stealth). Those have a reduced success change if you use troops. But ChampionCommander still uses troops by default. The "Analyze parties" button does show correct percentages though.

See screenshot for example. The default party only reaches 35%, but it would be possible to reach 95% with the available champions.
![wowscrnshot_082018_134442](https://user-images.githubusercontent.com/116314/44338809-71b09580-a47f-11e8-88be-2add79660248.jpg)

**Comment by alar77** [comment]
try raising basis-chance. You have 0, this could cause CC to pick a very low chance formation

**Comment by cremor** [comment]
I'll try. But if this is the problem, then the tutorial should be changed. Because right now it says "If instead you just want to always see the best available mission just set Bonus-Chance to 100% and Basis-Chance to 0%".
