### ISSUE TITLE
Estimated Time to Better Success Rates

### ISSUE THREAD

**Issue by Brightbrown** [alarofrunetotem/ChampionCommander#30]
One of the best features was knowing how long one had to wait to be able to increase the success chance, generally up to 200% chance. I waited for the last update but that did not change the situation... this essential function has been broken for a while (not sure if it started with 8.2 or was around prior to that) because it now ALWAYS says 7 days.

**Comment by alar77** [comment]
Work on this started

**Comment by Brightbrown** [comment]
Thank you, noticed it yeseday (came back from week's vacation in Canada!)

**Comment by alar77** [comment]
Actually, tolltip next mission previerw should work again, had you the chance to check it?

**Comment by alar77** [comment]
Fixed
