### ISSUE TITLE
Mission menu button floats off to the side

### ISSUE THREAD

**Issue by benkerwin** [alarofrunetotem/ChampionCommander#32]
![WoWScrnShot_083019_110524](https://user-images.githubusercontent.com/16943911/64031829-39727700-cb17-11e9-911b-70a5187b7921.jpg)

**Comment by alar77** [comment]
You are using a UI modifying addon which alters some frame I use
Alas, I have no time to play hide and seek with those addons, so I am afraid you will need to live with this.
