### ISSUE TITLE
Error when using "only ready" (but still works) and calculation problem(?)

### ISSUE THREAD

**Issue by steel-raven** [alarofrunetotem/ChampionCommander#33]
Hi there. 

Since the newest version I often get an error when clicking the "only ready" option (which you fixed for me). It works though, but kinda sucks getting the error everytime and have to close it. 

`Date: 2019-08-31 23:57:57
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\ChampionCommander\missionpage.lua line 258:
   attempt to concatenate field 'reason' (a nil value)
Debug:
   [C]: ?
   ChampionCommander\missionpage.lua:258: Update()
   ChampionCommander\missionpage.lua:358: CustomOnChange()
   ...ce\AddOns\ChampionCommander\libs\LibInit\factory.lua:232: OnChange()
   ...ce\AddOns\ChampionCommander\libs\LibInit\factory.lua:208:
      ...ce\AddOns\ChampionCommander\libs\LibInit\factory.lua:208
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.2
  Altoholic, vr191
  AskMrRobot, v79
  AstralKeys, v3.16
  AtlasLoot, vv8.10.00
  AtlasLootBattleforAzeroth, vv8.10.00
  AtlasLootBurningCrusade, vv8.10.00
  AtlasLootCataclysm, vv8.10.00
  AtlasLootClassic, vv8.10.00
  AtlasLootLegion, vv8.10.00
  AtlasLootMistsofPandaria, vv8.10.00
  AtlasLootWarlordsofDraenor, vv8.10.00
  AtlasLootWrathoftheLichKing, vv8.10.00
  AucAdvanced, v8.2.6338 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6368 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  Bartender4, v4.8.5
  BeanCounter, v8.2.6381 (SwimmingSeadragon)
  ChampionCommander, v1.2.1 80200
  DataStore, vr66
  DataStoreAchievements, vr48
  DataStoreAgenda, vr30
  DataStoreAuctions, vr51
  DataStoreCharacters, vr44
  DataStoreContainers, vr60
  DataStoreCrafts, vr83
  DataStoreCurrencies, vr39
  DataStoreGarrisons, vr25
  DataStoreInventory, vr54
  DataStoreMails, vr53
  DataStorePets, vr45
  DataStoreQuests, vr47
  DataStoreReputations, vr44
  DataStoreSpells, vr33
  DataStoreStats, vr32
  DataStoreTalents, vr62
  DBMCore, v8.2.15
  DBMDefaultSkin, v
  DBMPartyBfA, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6.3
  DejaCharacterStats, v820r201
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Enchantrix, v8.2.6373 (SwimmingSeadragon)
  ExRT, v4030
  HandyNotes, vv1.5.6
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesDraenorTreasures, v1.21
  HandyNotesGuild, v1.10
  HandyNotesWarfrontRares, v0.5.0
  Informant, v8.2.6374 (SwimmingSeadragon)
  MethodDungeonTools, v2.7.9
  MythicPlusTimer, v3.3
  Oilvl, v8.2.1
  Omen, v3.2.2
  Pawn, v2.2.46
  Prat30, v3.2.31
  Prat30Libraries, v
  Quartz, v3.5.1
  RaiderIO, v8.1.0 (v201908310600)
  RaiderIODBEUA, v
  RaiderIODBEUAR, v
  Raven, v
  SavedInstances, v8.2.2
  SexyMap, vv8.2.2
  Simulationcraft, v1.12.2
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  Titan, v5.18.2.80200
  TitanBag, v5.18.2.80200
  TitanClock, v5.18.2.80200
  TitanGold, v5.18.2.80200
  TitanGuild, v8.0.0.0
  TitanLocation, v5.18.2.80200
  TitanLootType, v5.18.2.80200
  TitanPerformance, v5.18.2.80200
  TitanRepair, v5.18.2.80200
  TitanVolume, v5.18.2.80200
  TitanXP, v5.18.2.80200
  WeakAuras, v2.14.6
  WeakAurasCompanion, v1.0.0
  WIM, v3.7.33
  ZPerl, v5.7.8
  ZPerlArcaneBar, v
  ZPerlCustomHighlight, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_deDE v8.2.0.80200 <none>
  (ck=bba)`

The second thing I noticed is a miscalculation for the percent:

![WoWScrnShot_090119_000145](https://user-images.githubusercontent.com/54681027/64069556-27debb80-cc4c-11e9-896a-bb3b57a50b21.jpg)

If you need any more infos or help, just tell me.

**Comment by alar77** [comment]
I see, should be a simple fix

**Comment by alar77** [comment]
Fixed 1.2.2
