### ISSUE TITLE
Success % wrong (with normal troops)

### ISSUE THREAD

**Issue by igorrebolj** [alarofrunetotem/ChampionCommander#36]
Im using both addons for that exact reason, calculations from CC are often dodgy. Also happens often addon pushes 1 champ and 2 troops without having anything to do with remaining champs / troops (i see using extra troops instead of champs as cost, since they need to be rebuild)

https://imgur.com/NnUWeJW

https://imgur.com/VGB4I2f

**Comment by alar77** [comment]
You can use the switch do not use troop to maximize champions'usage

**Comment by igorrebolj** [comment]
> You can use the switch do not use troop to maximize champions'usage

That sounds good in theory but never works out since you need troops to counter things in almost every mission. Just now have situation like this.

3 missions, only one at 200% (with any options, shown in square on right)
https://imgur.com/iB588Dk 
CC pushes dual troop single champ, when i go with "do not use troops" mission is not possible at all
https://imgur.com/UJhTTNn
And yet there is perfectly good dual champ single troop option:
https://imgur.com/H1s5QtF

**Comment by alar77** [comment]
You should check the analyze panel to have an insight of how the addon calculated setups. Also, there is a switch to limit the mac number of champions used (because the less champions you use, the more mission you can fire, providede you have plenty of troops)

**Comment by igorrebolj** [comment]
Bump, wrong % is back.
Latest version of addon
https://imgur.com/a/rSKv0xX

What is interesting, both addons show wrong %
