### ISSUE TITLE
Mini Map Icon Button

### ISSUE THREAD

**Issue by Cas2007** [alarofrunetotem/ChampionCommander#4]
I Can See The Mini Map Icon Button For Champion Commander. However There Is No Way To Move The Icon I Have Tried Everything.

Is There A Way To Move The Icon?

A Command Or Something?

Thank You

**Comment by alar77** [comment]
Doesnt shift click and drag work?

**Comment by alar77** [comment]
Btw, WHICH icon? There is no Icon for Champion Commander, now that I think about it

**Comment by alar77** [comment]
You are probably referring to the Blizzard one, Champion COmmander do not have a minimap icon

**Comment by alar77** [comment]
You are probably referring to the Blizzard one, Champion COmmander do not have a minimap icon

**Comment by alar77** [comment]
You are probably referring to the Blizzard one, Champion COmmander do not have a minimap icon
