### ISSUE TITLE
Add on broke in 9.0.1

### ISSUE THREAD

**Issue by lovs2build** [alarofrunetotem/ChampionCommander#44]
Can use view mission results but not quick and auto adding champions not working/loading.

**Comment by Vikirnoff** [comment]
Hello, I also got lua errors caused by the new patch. I'm going to list the one I got for this addon but also got errors for order hall commander too. :)  I hope this help. Thanks!! 

2x ChampionCommander\cache.lua:716: Usage: GetCurrencyTypes(garrType)
[string "=[C]"]: in function `GetCurrencyTypes'
[string "@ChampionCommander\cache.lua"]:716: in function <ChampionCommander\cache.lua:714>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:498: in function `InitializeAddon'
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:623: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML\UIParent.lua"]:495: in function `UIParentLoadAddOn'
[string "@FrameXML\UIParent.lua"]:685: in function `Garrison_LoadUI'
[string "@FrameXML\GarrisonBaseUtils.lua"]:369: in function `ShowGarrisonLandingPage'
[string "@FrameXML\Minimap.lua"]:701: in function `GarrisonLandingPage_Toggle'
[string "@FrameXML\Minimap.lua"]:693: in function <FrameXML\Minimap.lua:692>

**Comment by Alinnia** [comment]
I got the following error when opening the Missions from the mission table:

Message: ...ce\AddOns\ChampionCommander\libs\LibInit\factory.lua:278: attempt to call global 'MSA_DropDownMenu_Create' (a nil value)
Time: Thu Oct 15 12:48:58 2020
Count: 1
Stack: ...ce\AddOns\ChampionCommander\libs\LibInit\factory.lua:278: attempt to call global 'MSA_DropDownMenu_Create' (a nil value)
[string "=[C]"]: in function `MSA_DropDownMenu_Create'
[string "@Interface\AddOns\ChampionCommander\libs\LibInit\factory.lua"]:278: in function `DropDown'
[string "@Interface\AddOns\ChampionCommander\libs\LibInit\factory.lua"]:356: in function `Option'
[string "@Interface\AddOns\ChampionCommander\missionlist.lua"]:733: in function `Menu'
[string "@Interface\AddOns\ChampionCommander\missionlist.lua"]:796: in function <Interface\AddOns\ChampionCommander\missionlist.lua:791>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Interface\FrameXML\UIParent.lua"]:2893: in function `SetUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2699: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2606: in function <Interface\FrameXML\UIParent.lua:2602>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3457: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:1945: in function <Interface\FrameXML\UIParent.lua:1258>

Locals:

**Comment by Alinnia** [comment]
Get this error when viewing the Available Missions tab via the Missions minimap icon.

Message: ...ibInit\MSA-DropDownMenu-1.0\MSA-DropDownMenu-1.0.lua:212: attempt to call method 'SetBackdrop' (a nil value)
Time: Thu Oct 15 15:31:12 2020
Count: 1
Stack: ...ibInit\MSA-DropDownMenu-1.0\MSA-DropDownMenu-1.0.lua:212: attempt to call method 'SetBackdrop' (a nil value)
[string "=[C]"]: in function `SetBackdrop'
[string "@Interface\AddOns\ChampionCommander\libs\LibInit\MSA-DropDownMenu-1.0\MSA-DropDownMenu-1.0.lua"]:212: in function `CreateDropDownList'
[string "@Interface\AddOns\ChampionCommander\libs\LibInit\MSA-DropDownMenu-1.0\MSA-DropDownMenu-1.0.lua"]:390: in main chunk
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:495: in function `UIParentLoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:685: in function `Garrison_LoadUI'
[string "@Interface\FrameXML\GarrisonBaseUtils.lua"]:369: in function `ShowGarrisonLandingPage'
[string "@Interface\FrameXML\Minimap.lua"]:701: in function `GarrisonLandingPage_Toggle'
[string "@Interface\FrameXML\Minimap.lua"]:693: in function <Interface\FrameXML\Minimap.lua:692>
[string "=[C]"]: ?

Locals:

**Comment by Kithhurrn** [comment]
Same problem as OP. I get the buttons to complete all but nothing happens when I click it other than the mission table UI resets to Blizz default. Is it possible it's related to the changes listed here: https://github.com/Stanzilla/WoWUIBugs/wiki/9.0.1-Consolidated-UI-Changes#backdrop-system-changes ?

**Comment by Amadeus-** [comment]
The author is working on updates for ChampionCommander for sure (I'm not sure about the others.)    And, I'm sure there will be a release soon.

But, for now, as a stop-gap measure, you can download the zip file at [https://github.com/Amadeus-/ChampionCommander-Shadowlands/archive/master.zip](https://github.com/Amadeus-/ChampionCommander-Shadowlands/archive/master.zip) and then overwrite the contents of your current ChampionCommander folder with the contents within the zip file.  _(Please note that you'll need to open the zip file, go to the "ChampionCommander-Shadowlands-master" folder within the zip file, then extract all the files/folders within to your current ChampionCommander folder.   The files/folders should match exactly.)_   It's not perfect, but it removes the errors and gives you most of the functionality you need to enjoy the addon.

**Comment by Amadeus-** [comment]
The official release seems good now, so my stop-gap measure version is no longer required.   This issue could be closed.

**Comment by Cratis1831** [comment]
Updated to new version but still getting errors

**UPDATE:** It seems you need to have Garrison Commander AND Champion Commander installed for Champion Commander to function correctly.

`11x ...ceChampionCommander\libs\LibInit-56\factory.lua:278: attempt to call global 'MSA_DropDownMenu_Create' (a nil value)
[string "@ChampionCommander\libs\LibInit-56\factory.lua"]:278: in function `DropDown'
[string "@ChampionCommander\libs\LibInit-56\factory.lua"]:356: in function `Option'
[string "@ChampionCommander\missionlist.lua"]:739: in function `Menu'
[string "@ChampionCommander\missionlist.lua"]:802: in function <ChampionCommander\missionlist.lua:797>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:2893: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2699: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2606: in function <FrameXML\UIParent.lua:2602>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3457: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:1945: in function <FrameXML\UIParent.lua:1258>

Locals:
self = <table> {
 Checkbox = <function> defined @ChampionCommander\libs\LibInit\factory.lua:200
 Dropdown = <function> defined @ChampionCommander\libs\LibInit\factory.lua:273
 nonce = 17
 Button = <function> defined @ChampionCommander\libs\LibInit\factory.lua:246
 Option = <function> defined @ChampionCommander\libs\LibInit\factory.lua:342
 DropDown = <function> defined @ChampionCommander\libs\LibInit\factory.lua:273
 Slider = <function> defined @ChampionCommander\libs\LibInit\factory.lua:126
}
father = <unnamed> {
 0 = <userdata>
 OnEnter = <function> defined @ChampionCommander\ChampionCommander.lua:661
 Highlight = <unnamed> {
 }
 DefaultWidth = 220
 movable = false
 DragStop = <function> defined @ChampionCommander\ChampionCommander.lua:281
 ShowTT = <function> defined @ChampionCommander\ChampionCommander.lua:289
 DragStart = <function> defined @ChampionCommander\ChampionCommander.lua:278
 CounterTooltip = <function> defined @ChampionCommander\ChampionCommander.lua:256
 BorderTopLeft = <unnamed> {
 }
 OnDragStop = <function> defined @ChampionCommander\ChampionCommander.lua:699
 Dump = <function> defined @ChampionCommander\ChampionCommander.lua:298
 Bump = <function> defined @ChampionCommander\ChampionCommander.lua:266
 SetTitle = <function> defined @ChampionCommander\ChampionCommander.lua:682
 BorderBottomLeft = <unnamed> {
 }
 MakeMovable = <function> defined @ChampionCommander\ChampionCommander.lua:685
 Pulse = <unnamed> {
 }
 DebugOnLoad = <function> defined @ChampionCommander\ChampionCommander.lua:263
 Background = <unnamed> {
 }
 Tutorial = <unnamed> {
 }
 BorderTop = <unnamed> {
 }
 Title = <unnamed> {
 }
 OnLoad = <function> defined @ChampionCommander\ChampionCommander.lua:658
 BorderTopRight = <unnamed> {
 }
 BorderLeft = <unnamed> {
 }
 HideTT = <function> defined @ChampionCommander\ChampionCommander.lua:295
 Close = <unnamed> {
 }
 DumpData = <function> defined @ChampionCommander\ChampionCommander.lua:307
 BorderRight = <unnamed> {
 }
 AnchorTT = <function> defined @ChampionCommander\ChampionCommander.lua:284
 OnDragStart = <function> defined @ChampionCommander\ChampionCommander.lua:696
 Set = <function> defined @ChampionCommander\ChampionCommander.lua:272
 BorderBottom = <unnamed> {
 }
 BorderBottomRight = <unnamed> {
 }
 PinOpen = true
}
current = "Garrison_SortMissions_Original"
list = <table> {
 Garrison_SortMissions_HourlyXp = "Global approx. xp reward per hour"
 Garrison_SortMissions_Chance = "Success Chance"
 Garrison_SortMissions_Class = "Reward type"
 Garrison_SortMissions_Xp = "Global approx. xp reward"
 Garrison_SortMissions_Original = "Original method"
 Garrison_SortMissions_Level = "Level"
 Garrison_SortMissions_Age = "Expiration Time"
 Garrison_SortMissions_Duration = "Duration Time"
}
frame = <unnamed> {
 message = "Sort missions by:"
 maxwidth = 200
 widgetType = "Dropdown"
 SetOnChange = <function> defined @ChampionCommander\libs\LibInit\factory.lua:277
 tooltip = "Changes the sort order of missions in Mission panel"
 0 = <userdata>
 SetObj = <function> defined @ChampionCommander\libs\LibInit\factory.lua:106
}
name = "LibInitDropdown00017"
(*temporary) = nil
(*temporary) = "LibInitDropdown00017"
(*temporary) = <unnamed> {
 message = "Sort missions by:"
 maxwidth = 200
 widgetType = "Dropdown"
 SetOnChange = <function> defined @ChampionCommander\libs\LibInit\factory.lua:277
 tooltip = "Changes the sort order of missions in Mission panel"
 0 = <userdata>
 SetObj = <function> defined @ChampionCommander\libs\LibInit\factory.lua:106
}
(*temporary) = "attempt to call global 'MSA_DropDownMenu_Create' (a nil value)"
SetUp = <function> defined @Interf`

**Comment by Amadeus-** [comment]
> **UPDATE:** It seems you need to have Garrison Commander AND Champion Commander installed for Champion Commander to function correctly.

That lib should be located within /libs/libInit/MSA-DropDownMenu-1.0   ...and, it looks like it's being loaded properly via /libs/LibInit/LibInit.xml

I just tried ChampionCommander without any other addons loaded at all, and it worked just fine.   So, maybe you need to delete your addons/ChampionCommander and reinstall.   And, make sure it's coming with all libs.

**Comment by Mafiacow** [comment]
Even with the update, it's still not working for me. Tried reinstalling the addon, and I've already got Garrison Commander, but still nothing.
