### ISSUE TITLE
Italian localization shows what I think are korean symbols

### ISSUE THREAD

**Issue by Nespolazzo** [alarofrunetotem/ChampionCommander#5]
As title.
My UI is italian but even some of the text are in italian as well, many are in korean. Look the button below and the whole menu on the right.
![image](https://user-images.githubusercontent.com/42567847/44386593-3d8eb080-a523-11e8-93af-503d97b2807b.png)

**Comment by AlexDG89** [comment]
Actually the localization is wrong. The Addon select the itIT localization but the translation is wrong. 
In localization.lua:
> ...
> L=l:NewLocale(me,"itIT")
> if (L) then
> L["%1$d%% lower than %2$d%%. Lower %s"] = "%2$d%%보다 %1$d%% 낮습니다. %3$s 낮습니다"
> ...
> L=l:NewLocale(me,"koKR")
> if (L) then
> L["%1$d%% lower than %2$d%%. Lower %s"] = "%2$d%%보다 %1$d%% 낮습니다. %3$s 낮습니다"
> ...

Changin itIT to enUS in forcelocale.lua seems do nothing.

**Comment by alar77** [comment]
Fixed 1.1.0 Beta2
Se non vuoi scaricare la beta o ti da errore, prova a mettere
GAME_LOCALE="itIT"
in localization.lua, come primissima riga
