### ISSUE TITLE
LibInit.xml error

### ISSUE THREAD

**Issue by Ookami313** [alarofrunetotem/ChampionCommander#50]
Addon seems to work fine, but I'm getting a weird xml error when I log in.

4x Couldn't open ChampionCommander\libs\LibInit-62\LibInit.xml

**Comment by Venturic** [comment]
The problem is on PATH move file or correct the file embeds.xml: 
`$ grep 'LibInit.xml' * -Ri
embeds.xml:     <Include file="libs\LibInit\LibInit.xml"/>`
to 
`embeds.xml:     <Include file="libs\LibInit\LibInit\LibInit.xml"/>`
