### ISSUE TITLE
Missing Lib v1.3.1

### ISSUE THREAD

**Issue by Uggers** [alarofrunetotem/ChampionCommander#52]
I believe the latest version just release in the last hour has a missing lib;

`3x ...rfaceChampionCommander\ChampionCommander-1.3.1 90001.lua:14: ChampionCommander: Missing LibInit, please reinstall
[string "=[C]"]: in function `assert'
[string "@ChampionCommander\ChampionCommander-1.3.1 90001.lua"]:14: in main chunk
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML\UIParent.lua"]:495: in function `UIParentLoadAddOn'
[string "@FrameXML\UIParent.lua"]:685: in function `Garrison_LoadUI'
[string "@FrameXML\UIParent.lua"]:2176: in function <FrameXML\UIParent.lua:1258>

Locals:
(*temporary) = nil
(*temporary) = "ChampionCommander: Missing LibInit, please reinstall"
`

**Comment by gman4** [comment]
So that is why not loading at all?

**Comment by SoLoR1** [comment]
Its just an issue with how LibInit is pulled in to the package... easiest way to temporary fix it with new version is edit embeds.xml and edit path to LibInit with `<Include file="libs\LibInit\LibInit\LibInit.xml"/>`
