### ISSUE TITLE
Really wierd issue

### ISSUE THREAD

**Issue by Mortyfar** [alarofrunetotem/ChampionCommander#53]
I have been using this addon with great pleasure, however, I have stumbled over a really wierd issue.
When my main character tries to use the mission table i get this error (the error pops up as soon as the mouse hovers over any of the missions.):

Message: Interface\AddOns\ChampionCommander\cache.lua:402: attempt to index local 'reward' (a nil value)
Time: Wed Oct 28 12:13:41 2020
Count: 1
Stack: Interface\AddOns\ChampionCommander\cache.lua:402: attempt to index local 'reward' (a nil value)
[string "@Interface\AddOns\ChampionCommander\cache.lua"]:402: in function <Interface\AddOns\ChampionCommander\cache.lua:384>
[string "@Interface\AddOns\ChampionCommander\cache.lua"]:437: in function `Reward2Class'
[string "@Interface\AddOns\ChampionCommander\cache.lua"]:486: in function <Interface\AddOns\ChampionCommander\cache.lua:482>
[string "@Interface\AddOns\ChampionCommander\matchmaker.lua"]:589: in function `Match'
[string "@Interface\AddOns\ChampionCommander\matchmaker.lua"]:702: in function `?'
[string "@Interface\AddOns\ChampionCommander\missionlist.lua"]:604: in function <Interface\AddOns\ChampionCommander\missionlist.lua:588>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\ChampionCommander\missionlist.lua"]:633: in function `ReloadMissions'
[string "@Interface\AddOns\ChampionCommander\missionlist.lua"]:817: in function <Interface\AddOns\ChampionCommander\missionlist.lua:797>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Interface\FrameXML\UIParent.lua"]:2893: in function `SetUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2699: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2606: in function <Interface\FrameXML\UIParent.lua:2602>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3457: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:1945: in function <Interface\FrameXML\UIParent.lua:1258>

Locals: self = <table> {
 MAXLEVEL = <function> defined @Interface\AddOns\ChampionCommander\ChampionCommander.lua:137
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface\AddOns\ChampionCommander\libs\LibInit\Ace3\AceTimer-3.0\AceTimer-3.0.lua:147
 IsBlacklisted = <function> defined @Interface\AddOns\ChampionCommander\core.lua:169
 GetAverageLevels = <function> defined @Interface\AddOns\ChampionCommander\cache.lua:951
 allEquipments = <table> {
 }
 RebuildMissionCache = <function> defined @Interface\AddOns\ChampionCommander\cache.lua:938
 GetDataModule = <function> defined @Interface\AddOns\ChampionCommander\data.lua:14
 ActivateButton = <function> defined @Interface\AddOns\ChampionCommander\core.lua:203
 GetDifficultyColors = <function> defined @Interface\AddOns\ChampionCommander\core.lua:230
 GetMissionlistModule = <function> defined @Interface\AddOns\ChampionCommander\missionlist.lua:16
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\ChampionCommander\libs\LibInit\Ace3\AceAddon-3.0\AceAddon-3.0.lua:409
 MAXQUALITY = <function> defined @Interface\AddOns\ChampionCommander\ChampionCommander.lua:140
 GetResources = <function> defined @Interface\AddOns\ChampionCommander\cache.lua:751
 GetCacheModule = <function> defined @Interface\AddOns\ChampionCommander\cache.lua:16
 IsEnabled = <function> defined @Interface\AddOns\ChampionCommander\libs\LibInit\Ace3\AceAddon-3.0\AceAddon-3.0.lua:451
 GetCompletedMissionData = <function> defined @Interface\AddOns\ChampionCommander\autocomplete.lua:575
 MarkAsSeen = <function> defined @Interface\AddOns\ChampionCommander\core.lua:293
 ReloadMissions = <function> defined @Interface\AddOns\ChampionCommander\missionlist.lua:626
 RegisterMessage = <function> defined @Interface\AddOns\ChampionCommander\libs\LibInit\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\ChampionCommander\libs\LibInit\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Pulse = <function> defined @Interface\AddOns\ChampionCommander\missionlist.lua:702
 hooks = <table> {
 }
 db = <table> {
 }
 PauseApply = <function> defined @Interface\AddOns\ChampionCommander\missionlist.lua:555
 Apply = <function> defined @Interface\AddOns\ChampionCommander\missionlist

Now comes the wierd part, ALL my alts does NOT have this issue, the addon works with out fault.
I tried deleting the addon and making sure all files connected to the addon were deleted, reinstalled, and still it only bug out on my main char.
I have tried running this addon without any other addons as well, and still, it's the same wierd bug.
I really don't get it.
Any help would be much appreciated.
Thanks

Btw. had this issue before pre-patch as well. I can't remeber when this started.

**Comment by alar77** [comment]
Could it be a no reward mission?
