### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Roneasaurus** [alarofrunetotem/ChampionCommander#55]
happens when opening mission table in Boralis

Message: ...e\AddOns\GarrisonMissionManager\MissionUI_Shared.lua:53: attempt to call local 'GetCurrencyInfo' (a nil value)
Time: Sun Nov  8 16:28:54 2020
Count: 1
Stack: ...e\AddOns\GarrisonMissionManager\MissionUI_Shared.lua:53: attempt to call local 'GetCurrencyInfo' (a nil value)
[string "@Interface\AddOns\ChampionCommander\cache.lua"]:721: in function <Interface\AddOns\ChampionCommander\cache.lua:720>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:498: in function `InitializeAddon'
[string "@Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:623: in function <Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:495: in function `UIParentLoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:685: in function `Garrison_LoadUI'
[string "@Interface\FrameXML\UIParent.lua"]:1940: in function <Interface\FrameXML\UIParent.lua:1258>

Locals: self = <table> {
 OnInitialized = <function> defined @Interface\AddOns\ChampionCommander\cache.lua:720
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:367
 GARRISON_LANDINGPAGE_SHIPMENTS = <function> defined @Interface\AddOns\ChampionCommander\cache.lua:678
 baseName = "ChampionCommander"
 OnInitialize = <function> defined @Interface\AddOns\GarrisonCommander\libs\LibInit\LibInit.lua:374
 UnregisterAllEvents = <function> defined @Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 GetFollowerData = <function> defined @Interface\AddOns\ChampionCommander\cache.lua:298
 EnableModule = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface\AddOns\Ace3\AceTimer-3.0\AceTimer-3.0.lua:147
 IterateEmbeds = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:442
 EventsOff = <function> defined @Interface\AddOns\ChampionCommander\cache.lua:745
 SecureHook = <function> defined @Interface\AddOns\Ace3\AceHook-3.0\AceHook-3.0.lua:336
 defaultModuleLibraries = <table> {
 }
 DeleteFollower = <function> defined @Interface\AddOns\ChampionCommander\cache.lua:205
 Enable = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:294
 Clear = <function> defined @Interface\AddOns\ChampionCommander\cache.lua:530
 RawHookScript = <function> defined @Interface\AddOns\Ace3\AceHook-3.0\AceHook-3.0.lua:395
 GARRISON_FOLLOWER_CATEGORIES_UPDATED = <function> defined @Interface\AddOns\ChampionCommander\cache.lua:668
 CancelAllTimers = <function> defined @Interface\AddOns\Ace3\AceTimer-3.0\AceTimer-3.0.lua:160
 NewModule = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:235
 Events = <function> defined @Interface\AddOns\ChampionCommander\cache.lua:733
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:409
 GetModule = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:210
 Refresh = <function> defined @Interface\AddOns\ChampionCommander\cache.lua:706
 SecureHookScript = <function> defined @Interface\AddOns\Ace3\AceHook-3.0\AceHook-3.0.lua:410
 defaultModuleState = true
 TimeLeft = <function> defined @Interface\AddOns\Ace3\AceTimer-3.0\AceTimer-3.0.lua:172
 IsEnabled = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:451
 BuildMission = <function> defined @Interface\AddOns\ChampionCommander\cache.lua:227
 ScheduleTimer = <function> defined @Interface\AddOns\Ace3\AceTimer-3.0\AceTimer-3.0.lua:94
 Disable = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:314
 ScheduleRepeatingTimer = <function> defined @Interface\AddOns\Ace3\AceTimer-3.0\AceTimer-3.0.lua:129
 xDrawTroopStatus = <function> defi

**Comment by alar77** [comment]
Error is in GarrisonissionManager, not in ChampionCommander:
**Message: ...e\AddOns\GarrisonMissionManager\MissionUI_Shared.lua:53: attempt to call local 'GetCurrencyInfo' (a nil value)
Time: Sun Nov 8 16:28:54 2020**
