### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Imna1975** [alarofrunetotem/ChampionCommander#56]
1x ChampionCommander\missionlist.lua:994: bad argument #3 to 'SetFormattedText' (string expected, got nil)
[string "=[C]"]: in function `SetFormattedText'
[string "@ChampionCommander\missionlist.lua"]:994: in function `AdjustMissionButton'
[string "@ChampionCommander\widgets/MissionButton.lua"]:59: in function `SetMission'
[string "@ChampionCommander\widgets/MissionsList.lua"]:50: in function `AddMissionButton'
[string "@ChampionCommander\autocomplete.lua"]:407: in function `MissionAutoComplete'
[string "@ChampionCommander\autocomplete.lua"]:306: in function <ChampionCommander\autocomplete.lua:236>
[string "=(tail call)"]: ?
[string "@ChampionCommander\core.lua"]:204: in function <ChampionCommander\core.lua:204>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "%s
%s"
(*temporary) = "Mission läuft ab"
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by alar77** [comment]
Fixed 1.3.5
