### ISSUE TITLE
Unknown visual freeze/crash error

### ISSUE THREAD

**Issue by Sarelth** [alarofrunetotem/ChampionCommander#57]
Not sure why, but in the last couple hours the addon has been locking up my game and crashing it when I attempt to use the missile table. Have restarted the game a couple times now. 

In the table before it locks up the is graphical glitches, like no party preview and when info into a mission the champions do not appear in the mission. The percentage does not change if I try to move around champions manually.

**Comment by ukktu** [comment]
I have the same problem since yesterday. A reinstallation could not fix the errors.
As long as this great add-on does not work I switched to "War Plan". :/

**Comment by andrewbiller** [comment]
Check if you have a mission without reward in the end. It's currently bugged for those types of mission

**Comment by alar77** [comment]
Fixed in 1.3.9 (dry fix, could not make a no rewad mission pop)
