### ISSUE TITLE
A mission without reward causes freeze and crash

### ISSUE THREAD

**Issue by andrewbiller** [alarofrunetotem/ChampionCommander#58]
If you have a mission without reward (rare):

![WoWScrnShot_041621_174428](https://user-images.githubusercontent.com/4090466/115082197-e3189e80-9edb-11eb-938e-2f6b45726442.jpg)

it will freeze (loop) until blizzard disables addon.
Those are the errors:

![WoWScrnShot_041621_173859](https://user-images.githubusercontent.com/4090466/115082204-e57af880-9edb-11eb-9eba-3d8a35c692d6.jpg)

Those missions have bonus, but not reward. Maybe blizzard made something stinky in code.

![WoWScrnShot_041621_175131](https://user-images.githubusercontent.com/4090466/115082696-adc08080-9edc-11eb-89a0-70dfda0918f1.jpg)

**Comment by alar77** [comment]
I could not have a no reward mission to test, so I made a "dry" fix based on your debug info
Release as 1.3.9
