### ISSUE TITLE
dont work 9.1

### ISSUE THREAD

**Issue by clancyby** [alarofrunetotem/ChampionCommander#59]
dont work 9.1
ver 1.4

**Comment by alar77** [comment]
I can understand you are frustrated, but could you give more enlightenment? Some error messages?

**Comment by Kirbdawg** [comment]
It stopped working as of 9.1 release.   I can see the side bar, but nothing in the Blizard gui updates or changes when you add champions and it no long auto-populates champions.    I know this is old, but I still use it every day on a few of my characters... mostly for pet charms and items I can sell on the AH.  In case you choose not to update, I just want to thank you for all these great addons you've given us.   I still use Garrison commander every day on 28 toons to keep my playtime funded with gold.

Here's a couple of errors that happen just as it opens up:
1. **********************************************
Message: Interface\AddOns\ChampionCommander\cache.lua:908: attempt to compare number with nil
Time: Wed Jul  7 12:04:21 2021
Count: 1
Stack: Interface\AddOns\ChampionCommander\cache.lua:908: attempt to compare number with nil
[string "=[C]"]: ?
[string "@Interface\AddOns\ChampionCommander\cache.lua"]:908: in function `GetFullPermutations'
[string "@Interface\AddOns\ChampionCommander\matchmaker.lua"]:698: in function `?'
[string "@Interface\AddOns\ChampionCommander\missionlist.lua"]:604: in function <Interface\AddOns\ChampionCommander\missionlist.lua:588>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\ChampionCommander\missionlist.lua"]:426: in function `?'
[string "@Interface\AddOns\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua"]:90: in function `UpdateMissions'
[string "@Interface\AddOns\Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua"]:844: in function <...s\Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:843>
[string "=[C]"]: in function `Show'
[string "@Interface\FrameXML\UIParent.lua"]:2928: in function `SetUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2734: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2641: in function <Interface\FrameXML\UIParent.lua:2637>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3492: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:1978: in function <Interface\FrameXML\UIParent.lua:1287>
[string "=[C]"]: ?

Locals: 
2. *********************************************************************
Message: Interface\AddOns\ChampionCommander\cache.lua:908: attempt to compare number with nil
Time: Wed Jul  7 12:04:21 2021
Count: 1
Stack: Interface\AddOns\ChampionCommander\cache.lua:908: attempt to compare number with nil
[string "=[C]"]: ?
[string "@Interface\AddOns\ChampionCommander\cache.lua"]:908: in function `GetFullPermutations'
[string "@Interface\AddOns\ChampionCommander\matchmaker.lua"]:698: in function `?'
[string "@Interface\AddOns\ChampionCommander\missionlist.lua"]:604: in function <Interface\AddOns\ChampionCommander\missionlist.lua:588>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\ChampionCommander\missionlist.lua"]:426: in function `?'
[string "@Interface\AddOns\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua"]:90: in function `UpdateMissions'
[string "@Interface\AddOns\Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua"]:844: in function <...s\Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:843>
[string "=[C]"]: in function `Show'
[string "@Interface\FrameXML\UIParent.lua"]:2928: in function `SetUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2734: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2641: in function <Interface\FrameXML\UIParent.lua:2637>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3492: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:1978: in function <Interface\FrameXML\UIParent.lua:1287>
[string "=[C]"]: ?

Locals:

**Comment by alar77** [comment]
I released a tentative fix for this. Is a tentative because issue does not arise in my setup, so it's a sort of Band Aid more than a full solution

**Comment by Kirbdawg** [comment]
Looks good.  Thanks!
