### ISSUE TITLE
Mission list is not refreshed after starting a mission

### ISSUE THREAD

**Issue by cremor** [alarofrunetotem/ChampionCommander#6]
Whenever I start a mission, the mission list is not refreshed automatically. I have to toggle one setting to get it refreshed.

**Comment by alar77** [comment]
Fix attempt

**Comment by cremor** [comment]
@alar77 This is not fixed with 1.1.0-Beta-3. I still have to at least toggle a setting to get a refreshed list. Sometimes it's even required to completely reopen the window.
