### ISSUE TITLE
[EDIT: Not addon problem] 9.1 problems seem to be conflict with other addons

### ISSUE THREAD

**Issue by uroshnor23** [alarofrunetotem/ChampionCommander#60]
**[SOLVED with 1.4.1 update]**

I'm having the same problem on most of my toons, where you see the sidebar on the left but no other functionality.
However, on one of my toons, using a restricted list of addons from testing for a previous problem, works seemingly as normal. I will try loading my standard addons back in to the active list one by one and see if I can identify the problematic addon.

EDIT: Not an addon conflict after all, seems to be class based. Using the same list of addons, ChampionCommander works on some toons and not others:

GOOD:
Level 50 Worgen Warlock
Level 51 Gnome Mage
Level 51 Night Elf Druid
Level 51 Human Paladin
Level 52 Kul Tiran Druid
Level 60 Dwarf Shaman

BAD:
Level 50 Night Elf Hunter
Level 50 Draenei Hunter
Level 50 Dark Iron Dwarf Warrior
Level 51 Human Warrior
Level 60 Draenei Death Knight

Hope this helps!

**Comment by alar77** [comment]
I really appreciate youe effort but , assuming race is not an issue itself, my main is a dwarf Hunter and Champion Commander work flawlessly
I'd more likely assume a conflict in some kind of mission only some of your toons received (and mine didnt).
I also released a maintenance release addressing some possible weird data: 1.4.1
I am closing the ticket as parte of release process. Feel free to reopen inf issue is non fixed . In that case, check if there is some mission in common between non working toons
Thanks

**Comment by uroshnor23** [comment]
The 1.4.1 update seems to have fixed the problem; I checked several of the toons that had a difficulty and all are working now. Thanks!

-- MLJ




On July 11, 2021 at 1:42 AM, Giovanni G ***@***.***> wrote:






I really appreciate youe effort but , assuming race is not an issue itself, my main is a dwarf Hunter and Champion Commander work flawlessly
I'd more likely assume a conflict in some kind of mission only some of your toons received (and mine didnt).
I also released a maintenance release addressing some possible weird data: 1.4.1
I am closing the ticket as parte of release process. Feel free to reopen inf issue is non fixed . In that case, check if there is some mission in common between non working toons
Thanks
