### ISSUE TITLE
Addon causing screenfreezes

### ISSUE THREAD

**Issue by SuzanShaman** [alarofrunetotem/ChampionCommander#9]
I have to switch this addon off all the time. Every time I kill a mob, my screen freezes for a second. Same with mounting or clicking anything. Whenever I turn this addon off, the freezing is gone. Please fix this.

**Comment by alar77** [comment]
These kind of bugs are really hard to find. Nothing in OHC is related to killing thins, so I absolutely have no idea why this is happening to you.
Any other information you think could help me?
